[buildpack]
name = "Python (AltSchool Builpack)"

  [publish.Ignore]
  files = [
    "test/",
    ".gitignore",
    ".dockerignore",
    ".github/",
    "Dockerfile",
    "Pipfile",
    "Pipfile.lock"
  ]
